# Generated by Django 2.1.2 on 2018-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(unique=True)),
                ('rank', models.CharField(max_length=5)),
                ('icon_url_1', models.URLField()),
                ('icon_url_2', models.URLField()),
                ('card_title', models.CharField(max_length=30)),
                ('character_name', models.CharField(max_length=15)),
                ('japanese_name', models.CharField(max_length=15)),
                ('property', models.CharField(max_length=5)),
                ('center_effect', models.CharField(max_length=15)),
                ('smile', models.PositiveIntegerField()),
                ('pure', models.PositiveIntegerField()),
                ('cool', models.PositiveIntegerField()),
                ('active_condition', models.CharField(max_length=10)),
                ('active_skill', models.CharField(max_length=15)),
            ],
        ),
    ]
