# Generated by Django 2.1.2 on 2018-10-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0002_auto_20181005_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterMainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kor_name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('jap_name', models.CharField(max_length=20)),
                ('voice_actor', models.CharField(max_length=30)),
                ('grade', models.IntegerField()),
                ('birthday', models.CharField(max_length=10)),
                ('height', models.IntegerField()),
                ('three_size', models.CharField(max_length=15)),
                ('blood_type', models.CharField(max_length=3)),
                ('hobbies', models.CharField(max_length=30)),
            ],
        ),
    ]
