# Generated by Django 2.1.2 on 2018-10-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0003_charactermaininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermaininfo',
            name='blood_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='charactermaininfo',
            name='hobbies',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='charactermaininfo',
            name='voice_actor',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
