# Generated by Django 2.1.2 on 2018-10-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0004_auto_20181006_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermaininfo',
            name='kor_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
