# Generated by Django 2.1.2 on 2018-10-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0005_auto_20181006_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactermaininfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
