# Generated by Django 2.1.2 on 2018-10-08 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0008_cardleveleffect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardleveleffect',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.CardInfo'),
        ),
    ]
