# Generated by Django 2.1.2 on 2018-10-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0009_auto_20181008_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SKILL', '스킬 발동'), ('MENU', '메뉴 화면'), ('RANDOM', '랜덤 대사'), ('TOUCH', '터치시'), ('SPECTIME', '특정 시간'), ('SPECDATE', '특정 날짜'), ('ETC', '기타 사항')], default='ETC', max_length=8)),
                ('context', models.CharField(max_length=80)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.CardInfo')),
            ],
        ),
    ]
