# Generated by Django 2.1.2 on 2018-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0010_cardmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmessage',
            name='context',
            field=models.CharField(max_length=250),
        ),
    ]
