# Generated by Django 2.1.2 on 2018-10-11 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0012_cardpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('img_file', models.ImageField(upload_to='card_images')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.CardInfo')),
            ],
        ),
    ]
