# Generated by Django 2.1.2 on 2018-10-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0013_cardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='img_file',
            field=models.ImageField(upload_to='card_images/'),
        ),
    ]
