# Generated by Django 2.1.2 on 2018-10-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0014_auto_20181012_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='img_file',
            field=models.ImageField(upload_to='card_images'),
        ),
    ]
