# Generated by Django 2.1.2 on 2018-10-11 18:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0015_auto_20181012_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='img_file',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\KangDB\\lovelive_crawlin_native_app\\lovelive_crawlin_api\\media'), upload_to='images/main'),
        ),
    ]
