# Generated by Django 2.1.2 on 2018-10-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0016_auto_20181012_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='file_name',
        ),
        migrations.AddField(
            model_name='cardimage',
            name='img_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='img_file',
            field=models.ImageField(blank=True, upload_to='card/main'),
        ),
    ]
