# Generated by Django 2.1.2 on 2018-10-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0017_auto_20181012_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardimage',
            name='img_file',
            field=models.ImageField(blank=True, default='card/main/default_image.jpg', upload_to='card/main'),
        ),
    ]
