# Generated by Django 2.1.2 on 2018-10-16 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0018_auto_20181012_0847'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardIcon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.URLField(null=True)),
                ('img_file', models.ImageField(blank=True, default='card/icon/default_image.jpg', upload_to='card/icon')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.CardInfo')),
            ],
        ),
    ]
