# Generated by Django 2.1.2 on 2018-11-01 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0021_auto_20181027_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongCoverImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.URLField(null=True)),
                ('img_file', models.ImageField(blank=True, default='song/main/default_image.jpg', upload_to='song/main')),
            ],
        ),
        migrations.CreateModel(
            name='SongDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(max_length=10)),
                ('star_count', models.IntegerField()),
                ('level_value', models.IntegerField()),
                ('exp_value', models.IntegerField()),
                ('note_count', models.IntegerField()),
                ('destiny_count', models.IntegerField()),
                ('c_rank_score', models.IntegerField()),
                ('b_rank_score', models.IntegerField()),
                ('a_rank_score', models.IntegerField()),
                ('s_rank_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SongInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('kor_title', models.CharField(max_length=60)),
                ('jap_title', models.CharField(max_length=60)),
                ('type', models.CharField(max_length=10)),
                ('property', models.CharField(max_length=5)),
                ('unlock_level', models.IntegerField()),
                ('unlock_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='songdetail',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.SongInfo'),
        ),
        migrations.AddField(
            model_name='songcoverimage',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.SongInfo'),
        ),
    ]
