# Generated by Django 2.1.2 on 2018-11-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0022_auto_20181101_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcoverimage',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.SongInfo'),
        ),
    ]
