# Generated by Django 2.1.2 on 2018-11-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0023_auto_20181101_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(choices=[('KOR', '한국 서버'), ('JAP', '일본 서버')], default='JAP', max_length=3)),
                ('event_context', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('album_cut_score', models.PositiveIntegerField()),
                ('skill_cut_score', models.PositiveIntegerField()),
                ('skill_pivot_rank', models.PositiveIntegerField()),
                ('wake_up_cut_score', models.PositiveIntegerField()),
                ('wake_up_pivot_rank', models.PositiveIntegerField()),
                ('first_cut_score', models.PositiveIntegerField()),
                ('card_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.CardInfo')),
                ('song_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.SongInfo')),
            ],
        ),
    ]
