# Generated by Django 2.1.2 on 2018-11-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0024_eventinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinfo',
            name='event_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
