# Generated by Django 2.1.2 on 2018-11-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0025_eventinfo_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='song_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.SongInfo'),
        ),
    ]
