# Generated by Django 2.1.2 on 2018-11-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lovelive_api', '0026_auto_20181109_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinfo',
            name='card_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lovelive_api.CardInfo'),
        ),
    ]
